import {pool} from './db';
import {storage} from './storage';
import {sendAttendanceEventEmail} from './mail';
import {dateInZone} from '../shared/time-report';
import {timesheetLocation} from './timesheet-location';
export function localIso(instant:string|Date,tz:string){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(instant));const p=(type:string)=>parts.find(part=>part.type===type)!.value;return `${p('year')}-${p('month')}-${p('day')}T${p('hour')}:${p('minute')}:${p('second')}`;}
export function scheduledInstant(local:string,tz:string){if(/Z$|[+-]\d\d:\d\d$/.test(local))return Date.parse(local);const desired=Date.parse(local+'Z');let instant=desired;for(let i=0;i<3;i++)instant+=desired-Date.parse(localIso(new Date(instant),tz)+'Z');return instant;}
export function attendanceShift(entry:any,shifts:any[],tz:string){const linked=shifts.find(shift=>shift.id===entry.shiftId&&shift.employeeId===entry.employeeId);if(linked)return linked;const instant=Date.parse(entry.clockInAt);return shifts.filter(shift=>shift.employeeId===entry.employeeId&&shift.status!=='cancelled'&&Math.abs(instant-scheduledInstant(shift.scheduledStartAt,tz))<=6*3600000).sort((a,b)=>Math.abs(instant-scheduledInstant(a.scheduledStartAt,tz))-Math.abs(instant-scheduledInstant(b.scheduledStartAt,tz)))[0];}
export function isMissedShift(shift:any,entries:any[],tz:string,now:Date){const start=scheduledInstant(shift.scheduledStartAt,tz),end=scheduledInstant(shift.scheduledEndAt,tz);if(shift.status==='cancelled'||shift.status==='completed'||now.getTime()<start+6*3600000)return false;return !entries.some(entry=>entry.employeeId===shift.employeeId&&(entry.shiftId===shift.id||(Date.parse(entry.clockInAt)<=end&&Date.parse(entry.clockOutAt||now.toISOString())>=start)));}
const switches:Record<string,'alertEmployeeClockedIn'|'alertEmployeeClockedOut'|'alertLateClockIn'|'alertMissedShift'>={'clock-in':'alertEmployeeClockedIn','clock-out':'alertEmployeeClockedOut',late:'alertLateClockIn',missed:'alertMissedShift'};
async function queueEvent(company:any,cleaner:any,kind:string,key:string,details:string){if(!company[switches[kind]])return;const recipients=(await storage.getAdminsByCompany(company.id)).filter(admin=>admin.isActive&&admin.companyId===company.id&&admin.email?.trim());const seen=new Set<string>();const labels:any={'clock-in':'clocked in','clock-out':'clocked out',late:'clocked in late',missed:'missed a shift'};for(const admin of recipients){const email=admin.email!.trim().toLowerCase();if(seen.has(email))continue;seen.add(email);await pool.query(`INSERT INTO attendance_email_deliveries(company_id,recipient_id,recipient,event_key,kind,subject,body) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(event_key,recipient_id) DO NOTHING`,[company.id,admin.id,email,key,kind,`ClockField: ${cleaner.firstName} ${cleaner.lastName} ${labels[kind]}`,`${company.name}\nEmployee: ${cleaner.firstName} ${cleaner.lastName} (${cleaner.employeeId||''})\n${details}\nTimezone: ${company.timezone}\n\nView attendance: ${process.env.APP_URL||'https://clockfield.com'}/admin/attendance`]);}}
export async function queueAttendanceEvent(cleaner:any,entry:any,kind:'clock-in'|'clock-out',send=sendAttendanceEventEmail){
 const company=await storage.getCompany(cleaner.companyId);if(!company)return;
 const format=(value:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:company.timezone,year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(value));
 const [shifts,locations,schedules,clients]=await Promise.all([storage.getShiftsByCompany(company.id),storage.getLocationsByCompany(company.id),storage.getRecurringSchedulesByCompany(company.id),storage.getClientsByCompany(company.id)]);
 const shift=attendanceShift(entry,shifts,company.timezone);const date=dateInZone(entry.clockInAt,company.timezone);const location=timesheetLocation(entry,date,localIso(entry.clockInAt,company.timezone).slice(11,16),entry.clockOutAt?localIso(entry.clockOutAt,company.timezone).slice(11,16):localIso(entry.clockInAt,company.timezone).slice(11,16),locations,shifts,schedules,clients);
 const minutes=entry.clockOutAt?Math.max(0,Math.round((Date.parse(entry.clockOutAt)-Date.parse(entry.clockInAt))/60000)):0;
 const details=`Location: ${location}\nClock-in: ${format(entry.clockInAt)}${entry.clockOutAt?`\nClock-out: ${format(entry.clockOutAt)}\nHours worked: ${Math.floor(minutes/60)}h ${minutes%60}m`:''}`;
 await queueEvent(company,cleaner,kind,`${kind}:${entry.id}`,details);
 if(kind==='clock-in'&&shift){const late=Math.floor((Date.parse(entry.clockInAt)-scheduledInstant(shift.scheduledStartAt,company.timezone))/60000);if(late>=5)await queueEvent(company,cleaner,'late',`late:${entry.id}`,`${details}\nScheduled start: ${shift.scheduledStartAt.replace('T',' ')}\nMinutes late: ${late}`);}
 await deliverAttendanceEmails(send);
}
export async function deliverAttendanceEmails(send=sendAttendanceEventEmail){const {rows}=await pool.query(`WITH selected AS (SELECT id FROM attendance_email_deliveries WHERE (status='pending' AND next_attempt_at<=now()) OR (status='sending' AND claimed_at<now()-interval '5 minutes') ORDER BY id LIMIT 20 FOR UPDATE SKIP LOCKED) UPDATE attendance_email_deliveries d SET status='sending',claimed_at=now(),attempts=attempts+1 FROM selected WHERE d.id=selected.id RETURNING d.*`);await Promise.allSettled(rows.map(async(row:any)=>{try{const [company,admin]=await Promise.all([storage.getCompany(row.company_id),storage.getUser(row.recipient_id)]);if(!company?.[switches[row.kind]]||!admin?.isActive||admin.role!=='admin'||admin.companyId!==row.company_id||admin.email?.trim().toLowerCase()!==row.recipient){await pool.query("UPDATE attendance_email_deliveries SET status='cancelled' WHERE id=$1",[row.id]);return;}await send(row.recipient,row.subject,row.body);await pool.query("UPDATE attendance_email_deliveries SET status='sent',sent_at=now(),last_error=NULL WHERE id=$1",[row.id]);}catch{await pool.query("UPDATE attendance_email_deliveries SET status='pending',next_attempt_at=now()+interval '5 minutes',last_error='Email provider did not accept the message' WHERE id=$1",[row.id]);}}));return {processed:rows.length};}
export async function processAttendanceAlerts(now=new Date(),send=sendAttendanceEventEmail){
 const companies=await storage.getAllCompanies();for(const company of companies.filter(company=>company.alertMissedShift&&company.accountStatus!=='suspended')){
  await pool.query('INSERT INTO attendance_alert_activation(company_id) VALUES($1) ON CONFLICT DO NOTHING',[company.id]);const {rows:[activation]}=await pool.query('SELECT enabled_at FROM attendance_alert_activation WHERE company_id=$1',[company.id]);
  const [shifts,entries,employees,locations]=await Promise.all([storage.getShiftsByCompany(company.id),storage.getTimeEntriesByCompany(company.id),storage.getEmployeesByCompany(company.id),storage.getLocationsByCompany(company.id)]);
  for(const shift of shifts){const due=scheduledInstant(shift.scheduledStartAt,company.timezone)+6*3600000;if(!Number.isFinite(due)||due<new Date(activation.enabled_at).getTime()||due>now.getTime()||!isMissedShift(shift,entries,company.timezone,now))continue;const employee=employees.find(employee=>employee.id===shift.employeeId);if(!employee?.isActive)continue;await queueEvent(company,employee,'missed',`missed:${shift.id}`,`No attendance clock-in found six hours after scheduled start.\nScheduled start: ${shift.scheduledStartAt.replace('T',' ')}\nLocation: ${locations.find(location=>location.id===shift.locationId)?.name||shift.shiftLabel||'Assigned shift'}`);}
 }
 return deliverAttendanceEmails(send);
}
