import type {Express} from 'express';
import {storage} from './storage';import {pool} from './db';import {requireRole} from './auth';
import {payrollSnapshot} from './payroll-timesheets';import {createTimesheetWorkbook} from "./timesheet-workbook";
import {dateShift} from "../shared/payroll-cycle";
import {publicTimesheetSnapshot} from './public-timesheet';
import {dateInZone} from '../shared/time-report';
import {weeklyPayrollMinutes} from '../shared/payroll-math';import {validDate} from '../shared/payroll-cycle';
export async function generateAdminTimesheet(companyId:string,employeeId:string,start:string,end:string,adminId:string){
 const snapshot=await payrollSnapshot(companyId,start,employeeId,end);const company=await storage.getCompany(companyId);if(!company)throw Error('Company not found');
 const [entries,adjustments]=await Promise.all([storage.getTimeEntriesByCompany(companyId),storage.getAttendanceAdjustmentsByCompany(companyId)]);const totals=new Map<string,number>();for(const adjustment of adjustments)totals.set(adjustment.timeEntryId,(totals.get(adjustment.timeEntryId)||0)+adjustment.adjustmentMinutes);const enriched=entries.map(entry=>({...entry,totalAdjustmentMinutes:totals.get(entry.id)||0}));
 const frozen=snapshot.employees[0].rows.filter((row:any)=>row.id).map((row:any)=>({id:row.id,employeeId,clockInAt:row.clockInAt,clockOutAt:row.clockOutAt,status:"completed",totalAdjustmentMinutes:row.adjustmentMinutes}));const context=enriched.filter(entry=>{const date=dateInZone(entry.clockInAt,company.timezone);return date<start||date>end;});
 const minutes=weeklyPayrollMinutes([...context,...frozen],employeeId,start,end,company.timezone,company.overtimeEnabled,company.overtimeThresholdWeekly??40);const now=new Date().toISOString();
 const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT id FROM users WHERE id=$1 AND company_id=$2 FOR UPDATE',[employeeId,companyId]);const {rows:[existing]}=await client.query('SELECT * FROM timesheets WHERE company_id=$1 AND employee_id=$2 AND pay_period_start=$3 AND pay_period_end=$4 FOR UPDATE',[companyId,employeeId,start,end]);if(existing?.status==='approved'){await client.query('COMMIT');return await storage.getTimesheet(existing.id);}
 const data={companyId,employeeId,payPeriodStart:start,payPeriodEnd:end,payPeriodType:company.defaultPayPeriodType,status:'draft',totalWorkedMinutes:snapshot.employees[0].payableMinutes,regularMinutes:minutes.regularMinutes,overtimeMinutes:minutes.overtimeMinutes,totalShifts:minutes.entriesCount,generatedAt:now,updatedAt:now,adminGenerated:true,generatedBy:adminId,worksheetSnapshot:publicTimesheetSnapshot(snapshot),submittedAt:null,approvedAt:null,approvedByUserId:null};
 const snake=(key:string)=>key.replace(/[A-Z]/g,char=>'_'+char.toLowerCase());const keys=Object.keys(data);const values=Object.values(data).map(value=>typeof value==='object'&&value!==null?JSON.stringify(value):value);let row:any;
 if(existing){const result=await client.query(`UPDATE timesheets SET ${keys.map((key,index)=>`"${snake(key)}"=$${index+1}`).join(',')} WHERE id=$${keys.length+1} RETURNING id`,[...values,existing.id]);row=result.rows[0];}else{const result=await client.query(`INSERT INTO timesheets(${keys.map(key=>`"${snake(key)}"`).join(',')},created_at) VALUES(${keys.map((_,index)=>`$${index+1}`).join(',')},$${keys.length+1}) RETURNING id`,[...values,now]);row=result.rows[0];}
 await client.query('COMMIT');return await storage.getTimesheet(row.id);
 }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
}
export function registerGeneratedTimesheets(app:Express){
 app.get('/api/timesheets/current',requireRole('employee'),async(req,res)=>{const user=req.user as any;const list=await storage.getTimesheetsByEmployee(user.id);res.json(list.find(sheet=>sheet.companyId===user.companyId&&sheet.adminGenerated)||null);});
 app.get('/api/timesheets',requireRole('admin','employee'),async(req,res)=>{try{const user=req.user as any;const all=user.role==='admin'?await storage.getTimesheetsByCompany(user.companyId):await storage.getTimesheetsByEmployee(user.id);res.json(all.filter(sheet=>sheet.companyId===user.companyId&&(user.role==='admin'||sheet.adminGenerated)&&(!req.query.periodStart||sheet.payPeriodStart===req.query.periodStart)));}catch{res.status(500).json({message:'Could not load generated timesheets'});}});
 app.post('/api/timesheets/generate',requireRole('admin'),async(req,res)=>{try{const user=req.user as any;const {employeeId,periodStart,periodEnd}=req.body;if(!validDate(periodStart)||!validDate(periodEnd)||periodEnd<periodStart||Date.parse(periodEnd)-Date.parse(periodStart)>365*86400000)return res.status(400).json({message:'Select valid start and end dates, up to one year apart'});const employees=await storage.getEmployeesByCompany(user.companyId);const selected=employees.filter(employee=>employee.companyId===user.companyId&&employee.role==='employee'&&(employeeId?employee.id===employeeId:employee.isActive&&employee.loginEnabled));if(!selected.length)return res.status(404).json({message:'No matching cleaner found'});const results=[];for(const employee of selected)results.push(await generateAdminTimesheet(user.companyId,employee.id,periodStart,periodEnd,user.id));res.json(results);}catch{res.status(500).json({message:'Could not generate timesheets'});}});
 app.get('/api/timesheets/:id.xlsx',requireRole('admin','employee'),async(req,res)=>{try{const user=req.user as any,sheet=await storage.getTimesheet(String(req.params.id));if(!sheet||sheet.companyId!==user.companyId||(user.role==='employee'&&(sheet.employeeId!==user.id||!sheet.adminGenerated)))return res.status(404).json({message:'Timesheet not found'});const saved=sheet.worksheetSnapshot;if(!saved)return res.status(409).json({message:'No row-level snapshot was stored for this older timesheet'});const rows=saved.rows.map((row:any,index:number)=>({date:row.date,day:row.day,id:row.hours!==''?`saved-${index}`:null,startTime:row.start,endTime:row.end,endDate:row.end&&row.start&&row.end<row.start?dateShift(row.date,1):row.date,rawMinutes:Math.round(Number(row.hours||0)*60),payableMinutes:Math.round(Number(row.hours||0)*60),location:row.location}));const file=await createTimesheetWorkbook({company:{name:saved.companyName,timezone:saved.timezone,companyLogoUrl:saved.logo},period:{start:saved.start,end:saved.end,payday:null},employees:[{name:saved.employeeName,employeeNumber:saved.employeeNumber,rows,rawMinutes:saved.totalMinutes,payableMinutes:saved.totalMinutes}]});res.set({'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="timesheet-${String(saved.employeeNumber||'employee').replace(/[^a-zA-Z0-9_-]/g,'_')}-${saved.start}-${saved.end}.xlsx"`,'Cache-Control':'private, no-store'});res.send(file);}catch{res.status(500).json({message:'Could not download the generated timesheet'});}});
 app.get('/api/timesheets/:id',requireRole('admin','employee'),async(req,res)=>{try{const user=req.user as any,sheet=await storage.getTimesheet(String(req.params.id));if(!sheet||sheet.companyId!==user.companyId||(user.role==='employee'&&(sheet.employeeId!==user.id||!sheet.adminGenerated)))return res.status(404).json({message:'Timesheet not found'});res.json(sheet);}catch{res.status(500).json({message:'Could not load timesheet'});}});
 app.post('/api/timesheets/:id/submit',requireRole('employee'),async(req,res)=>{const user=req.user as any,sheet=await storage.getTimesheet(String(req.params.id));if(!sheet||sheet.companyId!==user.companyId||sheet.employeeId!==user.id||!sheet.adminGenerated)return res.status(404).json({message:'Timesheet not found'});if(sheet.status!=='draft')return res.status(409).json({message:'Only generated draft timesheets can be acknowledged'});res.json(await storage.updateTimesheet(sheet.id,{status:'submitted',submittedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));});
 app.post('/api/timesheets/:id/approve',requireRole('admin'),async(req,res)=>{const user=req.user as any;const {rows}=await pool.query("UPDATE timesheets SET status='approved',approved_at=$3,approved_by_user_id=$2,updated_at=$3 WHERE id=$1 AND company_id=$4 AND admin_generated=true AND status IN ('draft','submitted','needs_review') AND generated_at=$5 RETURNING id",[String(req.params.id),user.id,new Date().toISOString(),user.companyId,req.body.generatedAt||"" ]);if(!rows.length)return res.status(409).json({message:'Timesheet changed or is already approved. Refresh and review again.'});res.json(await storage.getTimesheet(rows[0].id));});
}
