import {storage} from './storage';
import {lineTotals,money} from '../shared/payroll-math';
import {validDate} from '../shared/payroll-cycle';
export function payRunInput(input:any,existing?:any){const data={name:String(input.name??existing?.name??'').trim(),periodStart:input.periodStart??existing?.periodStart,periodEnd:input.periodEnd??existing?.periodEnd,payDate:input.payDate??existing?.payDate,status:input.status??existing?.status??'draft',notes:input.notes??existing?.notes??null};if(!data.name||!validDate(data.periodStart)||!validDate(data.periodEnd)||!validDate(data.payDate)||data.periodEnd<data.periodStart||data.payDate<data.periodEnd)throw Error('Enter a name, valid period dates and a payday on or after the period end');if(!['draft','under_review','paid','closed'].includes(data.status))throw Error('Select a valid pay run status');if(!existing&&data.status!=='draft')throw Error('Create the pay run as a draft first');return data;}
export function financialLine(input:any,kind:'earning'|'deduction',existing:any={}){const allowed=kind==='earning'?['type','description','hours','rate','amount','displayOrder']:['type','description','amount','employerPaid','displayOrder'];const data:any={};for(const key of allowed)if(input[key]!==undefined)data[key]=input[key];const merged={...existing,...data};if(!String(merged.type||"").trim())throw Error("Select a line type");if(data.employerPaid!==undefined&&typeof data.employerPaid!=="boolean")throw Error("Employer-paid must be true or false");if(data.displayOrder!==undefined&&(!Number.isInteger(data.displayOrder)||data.displayOrder<0))throw Error("Enter a valid display order");if(!String(merged.description||'').trim())throw Error('Enter a line description');for(const key of ['amount',...(kind==='earning'?['hours','rate']:[])]){const value=merged[key];if(key!=='amount'&&(value===''||value==null)){if(key in data)data[key]=null;continue;}if(value===''||value==null||!Number.isFinite(Number(value))||Number(value)<0)throw Error('Enter valid non-negative amounts, hours and rates');if(key in data)data[key]=money(Number(value)).toFixed(2);}
 if(kind==='earning'&&(!existing.id||input.hours!==undefined||input.rate!==undefined)&&['regular','overtime'].includes(merged.type)&&merged.hours!=null&&merged.hours!==''&&merged.rate!=null&&merged.rate!=='')data.amount=money(Number(merged.hours)*Number(merged.rate)).toFixed(2);
 return data;}
export async function refreshPayStubTotals(id:string,actorId:string){const [earnings,deductions]=await Promise.all([storage.getPayStubEarnings(id),storage.getPayStubDeductions(id)]);const totals=lineTotals(earnings,deductions);const hours=(type?:string)=>earnings.filter(line=>!type||line.type===type).reduce((sum,line)=>sum+Number(line.hours||0),0).toFixed(2);return storage.updatePayStub(id,{grossPay:totals.grossPay.toFixed(2),totalDeductions:totals.totalDeductions.toFixed(2),netPay:totals.netPay.toFixed(2),regularHours:hours('regular'),overtimeHours:hours('overtime'),totalHours:hours(),updatedBy:actorId,updatedAt:new Date().toISOString()});}
export async function insertPayrollRow(client:any,table:'pay_stubs'|'pay_stub_earnings'|'pay_stub_deductions'|'pay_stub_audit_log',data:any){const keys=Object.keys(data);const snake=(key:string)=>key.replace(/[A-Z]/g,char=>'_'+char.toLowerCase());const {rows}=await client.query(`INSERT INTO ${table}(${keys.map(key=>`"${snake(key)}"`).join(',')}) VALUES(${keys.map((_,index)=>`$${index+1}`).join(',')}) RETURNING *`,Object.values(data));const row=rows[0];return Object.fromEntries(Object.entries(row).map(([key,value])=>[key.replace(/_([a-z])/g,(_,char)=>char.toUpperCase()),value]));}
