import type {Express} from 'express';import {pool} from './db';import {requireRole} from './auth';
import {financialLine,insertPayrollRow} from './payroll-documents';import {lineTotals} from '../shared/payroll-math';
const camel=(row:any)=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key.replace(/_([a-z])/g,(_,char)=>char.toUpperCase()),value]));
const fail=(message:string,status=400)=>{throw Object.assign(new Error(message),{status});};
async function update(client:any,id:string,data:any){const keys=Object.keys(data);const {rows}=await client.query(`UPDATE pay_stubs SET ${keys.map((key,index)=>`"${key.replace(/[A-Z]/g,char=>'_'+char.toLowerCase())}"=$${index+1}`).join(',')} WHERE id=$${keys.length+1} RETURNING *`,[...Object.values(data),id]);return camel(rows[0]);}
async function totals(client:any,stub:any,actorId:string,updateHours=false){const earnings=(await client.query('SELECT * FROM pay_stub_earnings WHERE pay_stub_id=$1',[stub.id])).rows.map(camel),deductions=(await client.query('SELECT * FROM pay_stub_deductions WHERE pay_stub_id=$1',[stub.id])).rows.map(camel);const result=lineTotals(earnings,deductions);const hours=(type?:string)=>earnings.filter((line:any)=>!type||line.type===type).reduce((sum:number,line:any)=>sum+Number(line.hours||0),0).toFixed(2);return update(client,stub.id,{grossPay:result.grossPay.toFixed(2),totalDeductions:result.totalDeductions.toFixed(2),netPay:result.netPay.toFixed(2),...(updateHours?{regularHours:hours('regular'),overtimeHours:hours('overtime'),totalHours:hours(),regularMinutesSnapshot:null,overtimeMinutesSnapshot:null,totalMinutesSnapshot:null}:{}),updatedBy:actorId,updatedAt:new Date().toISOString()});}
export function registerPayrollStubActions(app:Express){const run=(action:any)=>async(req:any,res:any)=>{let client:any;try{client=await pool.connect();await client.query('BEGIN');const {rows:[raw]}=await client.query('SELECT * FROM pay_stubs WHERE id=$1 AND company_id=$2 FOR UPDATE',[req.params.id,req.user.companyId]);if(!raw)fail('Pay stub not found',404);const stub=camel(raw),now=new Date().toISOString();const result=await action(client,stub,req,now);await client.query('COMMIT');res.json(result);}catch(error:any){if(client){try{await client.query('ROLLBACK');}catch{}}res.status(error.status||500).json({message:error.status?error.message:'Could not update the pay stub'});}finally{client?.release();}};
const editable=(stub:any)=>{if(!['draft','reviewed'].includes(stub.status))fail('Finalized and published pay stubs are locked',409);};
const audit=(client:any,stub:any,req:any,action:string,now:string,metadata:any=null)=>insertPayrollRow(client,'pay_stub_audit_log',{payStubId:stub.id,action,actorId:req.user.id,actorRole:'admin',metadataJson:metadata?JSON.stringify(metadata):null,createdAt:now});
app.patch('/api/payroll/pay-stubs/:id',requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{editable(stub);const result=await update(client,stub.id,{adminNotes:String(req.body.adminNotes??stub.adminNotes??''),updatedBy:req.user.id,updatedAt:now});await audit(client,stub,req,'updated',now);return result;}));
app.post('/api/payroll/pay-stubs/:id/recalculate',requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{editable(stub);const result=await totals(client,stub,req.user.id);if(Number(result.netPay)<0)fail('Deductions exceed gross pay');await audit(client,stub,req,'recalculated',now);return result;}));
app.post('/api/payroll/pay-stubs/:id/finalize',requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{editable(stub);const result=await totals(client,stub,req.user.id);if(Number(result.netPay)<0)fail('Deductions exceed gross pay');const finalized=await update(client,stub.id,{status:'finalized',finalizedAt:now,updatedBy:req.user.id,updatedAt:now});await audit(client,stub,req,'finalized',now);return finalized;}));
app.post('/api/payroll/pay-stubs/:id/publish',requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{if(!['finalized','confirmed_paid','published'].includes(stub.status))fail('Finalize the pay stub before publishing',409);if(!Number.isFinite(Number(stub.netPay))||Number(stub.netPay)<0)fail('Review the pay stub totals before publishing');const result=await update(client,stub.id,{status:stub.confirmedPaidAt?'confirmed_paid':'published',employeeVisibleAt:stub.employeeVisibleAt||now,updatedBy:req.user.id,updatedAt:now});await audit(client,stub,req,'published',now);return result;}));
app.post('/api/payroll/pay-stubs/:id/confirm-paid',requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{if(stub.confirmedPaidAt)return stub;if(!['finalized','published'].includes(stub.status))fail('Finalize the pay stub before confirming payment',409);if(!Number.isFinite(Number(stub.netPay))||Number(stub.netPay)<0)fail('Review the pay stub totals before confirming payment');const result=await update(client,stub.id,{status:'confirmed_paid',confirmedPaidAt:now,employeeVisibleAt:stub.employeeVisibleAt||now,updatedBy:req.user.id,updatedAt:now});await audit(client,stub,req,'confirmed_paid',now);const remaining=await client.query("SELECT id FROM pay_stubs WHERE pay_run_id=$1 AND status<>'voided' AND confirmed_paid_at IS NULL",[stub.payRunId]);if(!remaining.rows.length)await client.query("UPDATE pay_runs SET status='paid',updated_at=$2 WHERE id=$1 AND company_id=$3 AND status<>'closed'",[stub.payRunId,now,req.user.companyId]);return result;}));
app.post('/api/payroll/pay-stubs/:id/void',requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{if(stub.confirmedPaidAt)fail('Paid pay stubs stay locked. Use a separate correcting document.',409);if(!String(req.body.reason||'').trim())fail('Enter a reason for voiding the pay stub');const result=await update(client,stub.id,{status:'voided',voidedAt:now,employeeVisibleAt:null,updatedBy:req.user.id,updatedAt:now});await audit(client,stub,req,'voided',now,{reason:req.body.reason});return result;}));
for(const kind of ['earnings','deductions'] as const){const table=kind==='earnings'?'pay_stub_earnings':'pay_stub_deductions',type=kind==='earnings'?'earning':'deduction';
app.post(`/api/payroll/pay-stubs/:id/${kind}`,requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{editable(stub);let data;try{data=financialLine(req.body,type);}catch(error:any){fail(error.message);}const line=await insertPayrollRow(client,table,{...data,payStubId:stub.id});await totals(client,stub,req.user.id,kind==='earnings'&&data.hours!=null);await audit(client,stub,req,`${type}_added`,now);return line;}));
app.patch(`/api/payroll/pay-stubs/:id/${kind}/:lineId`,requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{editable(stub);const {rows:[raw]}=await client.query(`SELECT * FROM ${table} WHERE id=$1 AND pay_stub_id=$2`,[req.params.lineId,stub.id]);if(!raw)fail('Line not found in this pay stub',404);let data;try{data=financialLine(req.body,type,camel(raw));}catch(error:any){fail(error.message);}const keys=Object.keys(data);if(keys.length)await client.query(`UPDATE ${table} SET ${keys.map((key,index)=>`"${key.replace(/[A-Z]/g,char=>'_'+char.toLowerCase())}"=$${index+1}`).join(',')} WHERE id=$${keys.length+1} AND pay_stub_id=$${keys.length+2}`,[...Object.values(data),req.params.lineId,stub.id]);await totals(client,stub,req.user.id,kind==='earnings'&&req.body.hours!==undefined);await audit(client,stub,req,`${type}_updated`,now);return {updated:true};}));
app.delete(`/api/payroll/pay-stubs/:id/${kind}/:lineId`,requireRole('admin'),run(async(client:any,stub:any,req:any,now:string)=>{editable(stub);const result=await client.query(`DELETE FROM ${table} WHERE id=$1 AND pay_stub_id=$2 RETURNING id`,[req.params.lineId,stub.id]);if(!result.rows.length)fail('Line not found in this pay stub',404);await totals(client,stub,req.user.id,kind==='earnings');await audit(client,stub,req,`${type}_removed`,now);return {removed:true};}));
}
}
