// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/training-cards/Pulse.tsx": () => import("../components/mockups/training-cards/Pulse.tsx"),
  "./components/mockups/training-cards/Roster.tsx": () => import("../components/mockups/training-cards/Roster.tsx"),
  "./components/mockups/training-cards/Trail.tsx": () => import("../components/mockups/training-cards/Trail.tsx")
};
