import {useState,useEffect,useCallback} from "react";
import {useSearch} from "wouter";
import {useQuery,useMutation} from "@tanstack/react-query";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {useToast} from "@/hooks/use-toast";
import {apiRequest,queryClient} from "@/lib/queryClient";
import {formatLocalDate,localToday} from "@/lib/timezone";
import {dateShift,payrollPeriod} from "@shared/payroll-cycle";

const worksheetDate=(date:string)=>`${date.slice(5,7)}/${date.slice(8,10)}/${date.slice(0,4)}`;

function Worksheet({employee,period,company,onDirty}:{employee:any;period:any;company:any;onDirty:(id:string,dirty:boolean)=>void}) {
  const {toast}=useToast();const [drafts,setDrafts]=useState<Record<string,any>>({});const [selected,setSelected]=useState<any>();const [reason,setReason]=useState("");
  const save=useMutation({mutationFn:async()=>{const draft=drafts[selected.id];await apiRequest("POST",`/api/admin/attendance/payroll-timesheet/${selected.id}/adjust`,{payableMinutes:Math.round(Number(draft.hours)*60),expectedMinutes:selected.payableMinutes,startTime:draft.startTime,endTime:draft.endTime,reason});},onSuccess:()=>{setDrafts(values=>{const next={...values};delete next[selected.id];return next;});setSelected(undefined);setReason("");queryClient.invalidateQueries({queryKey:["payroll-timesheet"]});queryClient.invalidateQueries({queryKey:["/api/time-entries"]});toast({title:"Adjustment saved",description:"Original clock-in and clock-out records are preserved."});},onError:(error:any)=>toast({title:"Could not save",description:error.message,variant:"destructive"})});
  const hasDrafts=Object.keys(drafts).length>0;
  useEffect(()=>{onDirty(employee.id,hasDrafts);},[employee.id,hasDrafts,onDirty]);
  useEffect(()=>()=>onDirty(employee.id,false),[employee.id,onDirty]);
  const hours=(row:any)=>drafts[row.id]?.hours ?? (row.payableMinutes/60).toFixed(2);
  const edit=(row:any,key:string,value:string)=>setDrafts(values=>{const draft={startTime:row.startTime,endTime:row.endTime,hours:(row.payableMinutes/60).toFixed(2),...values[row.id],[key]:value};if(key!=="hours"&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(draft.startTime)&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(draft.endTime)){const minutes=(time:string)=>Number(time.slice(0,2))*60+Number(time.slice(3));const endDays=Math.round((Date.parse((row.endDate||row.date)+"T12:00:00Z")-Date.parse(row.date+"T12:00:00Z"))/86400000);const before=minutes(row.endTime)+endDays*1440-minutes(row.startTime);const after=minutes(draft.endTime)+endDays*1440-minutes(draft.startTime);draft.hours=(Math.max(0,row.payableMinutes+after-before)/60).toFixed(2);}return {...values,[row.id]:draft};});
  const total=employee.rows.reduce((sum:number,row:any)=>sum+(drafts[row.id]?Math.round(Number(drafts[row.id].hours||0)*60):row.payableMinutes),0);
  return <section className="border rounded-lg bg-white text-black overflow-hidden print:break-inside-avoid">
    <div className="p-5 grid grid-cols-1 sm:grid-cols-2 gap-4"><div>{company.companyLogoUrl&&<img src={company.companyLogoUrl} alt="Company logo" className="h-16 max-w-40 object-contain mb-3"/>}<p className="font-bold">Employee Name: <span className="font-normal">{employee.name}</span></p><p className="font-bold">Employee Number: <span className="font-normal">{employee.employeeNumber}</span></p></div><div className="sm:text-right self-end"><p className="font-bold">Period Start: <span className="font-normal">{worksheetDate(period.start)}</span></p><p className="font-bold">Period End: <span className="font-normal">{worksheetDate(period.end)}</span></p><p className="text-xs text-gray-600 mt-2">Payday: {formatLocalDate(period.payday)} · {company.timezone}</p></div></div>
    {employee.pendingEntries>0&&<p className="p-3 bg-amber-50 text-amber-800">{employee.pendingEntries} unfinished attendance shift(s) need review. Their hours are excluded until clock-out is recorded.</p>}
    <div className="overflow-x-auto"><table className="w-full min-w-[850px] border-collapse text-sm"><thead><tr className="text-base font-bold border-y"><th className="p-3 text-left">Date</th><th className="p-3 text-left">Day</th><th className="p-3">Start Time</th><th className="p-3">End Time</th><th className="p-3 bg-gray-200 border-x-2 border-black">Hours Worked</th><th className="p-3 text-left">Location</th><th className="print:hidden" /></tr></thead><tbody>{employee.rows.map((row:any,index:number)=><tr key={row.id||row.date} className="border-b border-gray-200"><td className="px-3 py-2">{row.date.slice(5,7)}/{row.date.slice(8)}/{row.date.slice(0,4)}</td><td className={`px-3 py-2 font-semibold ${row.day==="Monday"?"bg-orange-400":""}`}>{row.day}</td><td className="p-1"><input aria-label={`${employee.name} ${row.date} start time ${index}`} type="text" inputMode="numeric" maxLength={5} placeholder="HH:MM" value={drafts[row.id]?.startTime ?? row.startTime} disabled={!row.id} onChange={event=>edit(row,"startTime",event.target.value)} className="w-28 mx-auto block bg-transparent text-center p-1 disabled:opacity-40"/></td><td className="p-1"><input aria-label={`${employee.name} ${row.date} end time ${index}`} type="text" inputMode="numeric" maxLength={5} placeholder="HH:MM" value={drafts[row.id]?.endTime ?? row.endTime} disabled={!row.id} onChange={event=>edit(row,"endTime",event.target.value)} className="w-28 mx-auto block bg-transparent text-center p-1 disabled:opacity-40"/></td><td className="bg-gray-200 border-x-2 border-black p-1" title={`Recorded: ${(row.rawMinutes/60).toFixed(2)}h. Actual times: ${row.actualStartTime||"—"}–${row.actualEndTime||"—"}. Saved adjustment: ${row.adjustmentMinutes||0} minutes.`}><input aria-label={`${employee.name} ${row.date} hours ${index}`} type="number" min="0" step="0.01" value={row.id?hours(row):""} disabled={!row.id} onChange={event=>edit(row,"hours",event.target.value)} className="w-24 block mx-auto bg-transparent text-right p-1 font-semibold"/><span className="sr-only">Recorded: {row.rawMinutes} minutes</span></td><td className="px-3 py-2">{row.location}</td><td className="px-2 print:hidden">{drafts[row.id]&&<Button size="sm" disabled={drafts[row.id].hours === "" || !Number.isFinite(Number(drafts[row.id].hours)) || Number(drafts[row.id].hours)<0 || !/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(drafts[row.id].startTime) || !/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(drafts[row.id].endTime)} onClick={()=>{setSelected(row);setReason("");}}>Save</Button>}</td></tr>)}</tbody><tfoot><tr><td colSpan={4} className="p-3 text-right font-bold">Total Hours:</td><td className="p-3 bg-gray-200 border-2 border-black text-right font-bold">{(total/60).toFixed(2)}</td><td colSpan={2} className="px-3 text-xs">{Math.floor(total/60)}h {total%60}m · Recorded: {(employee.rawMinutes/60).toFixed(2)}h</td></tr></tfoot></table></div>
    <div className="bg-yellow-300 px-4 py-3 text-sm font-semibold">NOTE: Enter times like 17:00 and 20:00. Save with a reason to apply an adjustment. Downloads and emails include saved hours.</div>
    {Object.keys(drafts).length>0&&<p className="p-3 text-sm text-amber-800 bg-amber-50">Unsaved edits are shown in the total. Save or discard them before downloading. <Button variant="outline" size="sm" onClick={()=>setDrafts({})}>Discard unsaved edits</Button></p>}
    <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(undefined);}}><DialogContent><DialogHeader><DialogTitle>Save hours adjustment</DialogTitle></DialogHeader><p className="text-sm">{employee.name} · {selected?.date}. Recorded hours remain unchanged. This adds a separate adjustment with your name and reason.</p><Label htmlFor={`reason-${employee.id}`}>Reason</Label><Input id={`reason-${employee.id}`} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Explain the correction"/><Button disabled={!reason.trim()||save.isPending} onClick={()=>save.mutate()}>Confirm adjustment</Button></DialogContent></Dialog>
  </section>;
}

export default function PayrollTimesheetPage(){
  const {toast}=useToast();const {data:company}=useQuery<any>({queryKey:["/api/company"]});
  const [dirtyEmployees,setDirtyEmployees]=useState<Record<string,boolean>>({});const onDirty=useCallback((id:string,dirty:boolean)=>setDirtyEmployees(current=>current[id]===dirty?current:{...current,[id]:dirty}),[]);const hasUnsaved=Object.values(dirtyEmployees).some(Boolean);
  const queryStart=new URLSearchParams(useSearch()).get("start");const [chosenStart,setChosenStart]=useState(queryStart||"");const [employeeId,setEmployeeId]=useState("all");const [scheduleOpen,setScheduleOpen]=useState(false);const [days,setDays]=useState<number[]>([2,4]);const [hour,setHour]=useState(9);const [scheduleEnabled,setScheduleEnabled]=useState(false);
  const current=payrollPeriod(company?.payrollCycleStartDate||"2026-09-21",localToday(company?.timezone||"America/Winnipeg"));const start=chosenStart||current.start;
  const {data,isLoading,isError}=useQuery<any>({queryKey:["payroll-timesheet",start,employeeId],queryFn:async()=>{const response=await apiRequest("GET",`/api/admin/attendance/payroll-timesheet?${new URLSearchParams({start,employeeId})}`);return response.json();},enabled:!!company});
  const {data:employees=[]}=useQuery<any[]>({queryKey:["/api/employees"]});
  const configure=useMutation({mutationFn:()=>apiRequest("PATCH","/api/admin/attendance/payroll-schedule",{anchor:company.payrollCycleStartDate||"2026-09-21",summaryDays:days.length?days:[2,4],hour,enabled:scheduleEnabled}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["/api/company"]});queryClient.invalidateQueries({queryKey:["payroll-timesheet"]});setScheduleOpen(false);toast({title:"Payroll summaries enabled"});},onError:(error:any)=>toast({title:"Could not save",description:error.message,variant:"destructive"})});
  return <div className="p-4 md:p-6 space-y-5"><div><h1 className="text-2xl font-bold">Timesheets</h1><p className="text-sm text-muted-foreground">Review a two-week period and save deliberate adjustments. Original attendance records are preserved.</p></div>
    <div className="flex flex-wrap items-center gap-2"><Button variant="outline" disabled={hasUnsaved} onClick={()=>setChosenStart(dateShift(start,-14))}>Previous period</Button><span className="font-semibold px-2">{formatLocalDate(start)} – {formatLocalDate(dateShift(start,13))}</span><Button variant="outline" disabled={hasUnsaved} onClick={()=>setChosenStart(dateShift(start,14))}>Next period</Button><Button variant="ghost" disabled={hasUnsaved} onClick={()=>setChosenStart(dateShift(current.start,-14))}>Last closed period</Button><Button variant="ghost" disabled={hasUnsaved} onClick={()=>setChosenStart(current.start)}>Current period</Button></div>
    <div className="flex flex-wrap gap-3 items-center"><Select value={employeeId} onValueChange={setEmployeeId} disabled={hasUnsaved}><SelectTrigger className="w-72" aria-label="Timesheet employee"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All employees</SelectItem>{employees.map(employee=><SelectItem key={employee.id} value={employee.id}>{employee.firstName} {employee.lastName} ({employee.employeeId})</SelectItem>)}</SelectContent></Select>{data&&!hasUnsaved?<Button asChild><a href={`/api/admin/attendance/payroll-timesheet.xlsx?${new URLSearchParams({start,employeeId})}`} download>Download editable Excel</a></Button>:<Button disabled>Download editable Excel</Button>}</div>
    {company&&<div className="border rounded-lg p-3 flex flex-wrap gap-3 items-center text-sm"><span>Payday: <b>{formatLocalDate(dateShift(start,18))}</b></span><span>{company.payrollSummaryEnabled?`Admin summaries: ${company.payrollSummaryDays.map((day:number)=>formatLocalDate(dateShift(start,13+day))).join(" and ")} at ${String(company.payrollSummaryHour).padStart(2,"0")}:00 ${company.timezone}`:"Automated payroll summaries are not enabled yet."}</span><Button size="sm" variant="outline" onClick={()=>{setDays(company.payrollSummaryDays||[2,4]);setHour(company.payrollSummaryHour??9);setScheduleEnabled(company.payrollSummaryEnabled??false);setScheduleOpen(true);}}>Email schedule</Button></div>}
    {isLoading&&<p>Loading timesheets…</p>}{isError&&<p role="alert" className="text-destructive">Could not load timesheets. Refresh and try again.</p>}
    {employeeId === "all" && data ? <div className="rounded-lg border overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted"><tr><th className="p-3 text-left">Employee</th><th className="p-3 text-left">Employee number</th><th className="p-3 text-right">Recorded hours</th><th className="p-3 text-right">Payable hours</th></tr></thead><tbody>{data.employees.map((employee:any)=><tr key={employee.id} className="border-t"><td className="p-3"><button className="text-primary underline" onClick={()=>setEmployeeId(employee.id)}>{employee.name}</button></td><td className="p-3">{employee.employeeNumber}</td><td className="p-3 text-right">{(employee.rawMinutes/60).toFixed(2)}</td><td className="p-3 text-right font-semibold">{(employee.payableMinutes/60).toFixed(2)}{employee.pendingEntries>0&&<span className="block text-xs text-amber-700">{employee.pendingEntries} unfinished shift(s)</span>}</td></tr>)}</tbody><tfoot className="border-t bg-muted font-semibold"><tr><td colSpan={2} className="p-3">Total hours</td><td className="p-3 text-right">{(data.employees.reduce((sum:number,employee:any)=>sum+employee.rawMinutes,0)/60).toFixed(2)}</td><td className="p-3 text-right">{(data.employees.reduce((sum:number,employee:any)=>sum+employee.payableMinutes,0)/60).toFixed(2)}</td></tr></tfoot></table></div> : data?.employees.map((employee:any)=><Worksheet key={`${start}-${employee.id}`} employee={employee} period={data.period} company={data.company} onDirty={onDirty}/>)}
    <Dialog open={scheduleOpen} onOpenChange={setScheduleOpen}><DialogContent><DialogHeader><DialogTitle>Payroll summary emails</DialogTitle></DialogHeader><p className="text-sm">Monday–Sunday periods repeat every 14 days. Payday is the following Friday. Summaries go to active company admins.</p><label className="flex gap-2 font-semibold"><input type="checkbox" checked={scheduleEnabled} onChange={event=>setScheduleEnabled(event.target.checked)}/>Enable automated payroll summaries</label>{[{day:2,label:`Tuesday after closing (${formatLocalDate(dateShift(start,15))})`},{day:4,label:`Thursday before payday (${formatLocalDate(dateShift(start,17))})`}].map(option=><label key={option.day} className="flex gap-2"><input type="checkbox" checked={days.includes(option.day)} onChange={event=>setDays(event.target.checked?[...days,option.day]:days.filter(day=>day!==option.day))}/>{option.label}</label>)}<Label htmlFor="summary-hour">Hour in {company?.timezone}</Label><Input id="summary-hour" type="number" min="0" max="23" value={hour} onChange={event=>setHour(Number(event.target.value))}/><Button disabled={(scheduleEnabled&&!days.length)||configure.isPending} onClick={()=>configure.mutate()}>Save email schedule</Button></DialogContent></Dialog>
  </div>;
}
