import assert from 'node:assert/strict';
import {normalizeCompanyGeography} from '../server/company-geography';
import {scheduledInstant,isMissedShift,queueAttendanceEvent,deliverAttendanceEmails,processAttendanceAlerts} from '../server/attendance-alerts';
import {storage} from '../server/storage';import {pool} from '../server/db';
assert.deepEqual(normalizeCompanyGeography({country:'CA',province:'MB',city:'Winnipeg,',timezone:'America/Winnipeg'}),{country:'CA',province:'MB',city:'Winnipeg',timezone:'America/Winnipeg'});
assert.throws(()=>normalizeCompanyGeography({country:'CA',province:'MB',city:'Toronto'}));assert.throws(()=>normalizeCompanyGeography({country:'CA',province:'MB',city:'Winnipeg',timezone:'America/Toronto'}));
assert.equal(new Date(scheduledInstant('2026-10-05T17:00:00','America/Winnipeg')).toISOString(),'2026-10-05T22:00:00.000Z');
assert.equal(new Date(scheduledInstant('2026-11-02T17:00:00','America/Winnipeg')).toISOString(),'2026-11-02T23:00:00.000Z');
const company={id:'c',name:'Company',timezone:'America/Winnipeg',alertEmployeeClockedIn:true,alertLateClockIn:true,alertEmployeeClockedOut:true,alertMissedShift:true};
const cleaner={id:'e',companyId:'c',firstName:'Test',lastName:'Cleaner',employeeId:'EMP-1',isActive:true};
const admin={id:'a',role:'admin',companyId:'c',email:'admin@example.com',isActive:true};
const shift={id:'s',companyId:'c',employeeId:'e',shiftDate:'2026-10-05',scheduledStartAt:'2026-10-05T17:00:00',scheduledEndAt:'2026-10-05T23:00:00',locationId:'loc',status:'scheduled'};
assert.equal(isMissedShift(shift,[],'America/Winnipeg',new Date('2026-10-06T03:59:59Z')),false);
assert.equal(isMissedShift(shift,[],'America/Winnipeg',new Date('2026-10-06T04:00:00Z')),true);
assert.equal(isMissedShift(shift,[{employeeId:'e',clockInAt:'2026-10-05T22:05:00Z'}],'America/Winnipeg',new Date('2026-10-06T04:00:00Z')),false);
const deliveries:any[]=[];let allowPending=true;let entries:any[]=[];
Object.assign(storage,{getCompany:async()=>company,getAdminsByCompany:async()=>[admin,{...admin,id:'duplicate',email:'ADMIN@example.com'},{...admin,id:'inactive',isActive:false},{...admin,id:'foreign',companyId:'other'}],getUser:async()=>admin,getShiftsByCompany:async()=>[shift],getLocationsByCompany:async()=>[{id:'loc',name:'Olympic'}],getRecurringSchedulesByCompany:async()=>[],getClientsByCompany:async()=>[],getEmployeesByCompany:async()=>[cleaner],getAllCompanies:async()=>[company],getTimeEntriesByCompany:async()=>entries});
(pool as any).query=async(sql:string,args:any[]=[])=>{if(sql.startsWith('INSERT INTO attendance_email_deliveries')){if(!deliveries.some(row=>row.event_key===args[3]&&row.recipient_id===args[1]))deliveries.push({id:deliveries.length+1,company_id:args[0],recipient_id:args[1],recipient:args[2],event_key:args[3],kind:args[4],subject:args[5],body:args[6],status:'pending'});return {rows:[]};}if(sql.startsWith('WITH selected')){const selected=allowPending?deliveries.filter(row=>row.status==='pending'):[];selected.forEach(row=>row.status='sending');return {rows:selected};}if(sql.includes("status='sent'")){deliveries.find(row=>row.id===args[0]).status='sent';return {rows:[]};}if(sql.includes("status='pending'")){deliveries.find(row=>row.id===args[0]).status='pending';return {rows:[]};}if(sql.includes("status='cancelled'")){deliveries.find(row=>row.id===args[0]).status='cancelled';return {rows:[]};}if(sql.startsWith('SELECT enabled_at'))return {rows:[{enabled_at:'2026-10-05T00:00:00Z'}]};return {rows:[]};};
const sent:any[]=[];const send=async(to:string,subject:string,body:string)=>{sent.push({to,subject,body});};
const entry={id:'entry',employeeId:'e',clockInAt:'2026-10-05T22:05:00Z',shiftId:'s',locationId:'loc'};
await queueAttendanceEvent(cleaner,entry,'clock-in',send);assert.equal(sent.length,2);assert.ok(sent.some(mail=>mail.body.includes('Minutes late: 5')));assert.ok(sent.every(mail=>mail.to==='admin@example.com'));await queueAttendanceEvent(cleaner,entry,'clock-in',send);assert.equal(sent.length,2);
await queueAttendanceEvent(cleaner,{...entry,id:'early',clockInAt:'2026-10-05T22:04:59Z'},'clock-in',send);assert.equal(sent.length,3);
await queueAttendanceEvent(cleaner,{...entry,clockOutAt:'2026-10-06T03:12:00Z'},'clock-out',send);assert.ok(sent.at(-1).body.includes('Hours worked: 5h 7m'));
await queueAttendanceEvent(cleaner,{...entry,id:'retry',clockOutAt:'2026-10-06T03:12:00Z'},'clock-out',async()=>{throw Error('provider unavailable');});assert.ok(deliveries.some(row=>row.status==='pending'));await deliverAttendanceEmails(send);assert.ok(deliveries.every(row=>row.status==='sent'));
await processAttendanceAlerts(new Date('2026-10-06T04:00:00Z'),send);const missed=sent.filter(mail=>mail.subject.includes('missed a shift'));assert.equal(missed.length,1);await processAttendanceAlerts(new Date('2026-10-06T04:05:00Z'),send);assert.equal(sent.filter(mail=>mail.subject.includes('missed a shift')).length,1);
company.alertEmployeeClockedOut=false;const count=sent.length;await queueAttendanceEvent(cleaner,{...entry,id:'disabled',clockOutAt:'2026-10-06T03:12:00Z'},'clock-out',send);assert.equal(sent.length,count);
console.log('PASS: country/province/city validation, Winnipeg daylight saving, five-minute lateness, six-hour missed threshold, all active admin recipients, duplicate suppression, clock-out hours, failed send retries and disabled switches.');
