import {dateInZone,entryMinutes} from './time-report';
import {dateShift} from './payroll-cycle';
export const money=(value:number)=>Math.round((value+Math.sign(value)*Number.EPSILON*Math.max(1,Math.abs(value)))*100)/100;
function localMidnight(date:string,timezone:string){const target=Date.parse(date+"T00:00:00Z");let instant=target;for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(new Date(instant));const value=(type:string)=>parts.find(part=>part.type===type)!.value;instant+=target-Date.parse(`${value("year")}-${value("month")}-${value("day")}T${value("hour")}:${value("minute")}:${value("second")}Z`);}return instant;}
export function weeklyPayrollMinutes(entries:any[],employeeId:string,start:string,end:string,timezone:string,overtimeEnabled:boolean,thresholdHours=40){
 const segments:Array<{week:string;instant:number;minutes:number;selected:boolean;id:string}>=[];let entriesCount=0;
 for(const entry of entries.filter(entry=>entry.employeeId===employeeId&&entry.status==="completed"&&entry.clockOutAt)){const date=dateInZone(entry.clockInAt,timezone),selected=date>=start&&date<=end,payable=entryMinutes(entry).payable,from=Date.parse(entry.clockInAt),to=Date.parse(entry.clockOutAt);if(selected)entriesCount++;let cursor=from,allocated=0;
  do{const local=dateInZone(new Date(cursor),timezone),day=new Date(local+"T12:00:00Z").getUTCDay(),week=dateShift(local,-((day+6)%7)),boundary=localMidnight(dateShift(week,7),timezone),until=Math.min(to,boundary),cumulative=to>from?Math.round(payable*(until-from)/(to-from)):payable;segments.push({week,instant:cursor,minutes:Math.max(0,cumulative-allocated),selected,id:String(entry.id||"")});allocated=cumulative;if(until<=cursor)break;cursor=until;}while(cursor<to);
 }
 const weeks=new Map<string,number>();let regularMinutes=0,overtimeMinutes=0,totalMinutes=0;const threshold=Math.max(0,Number(thresholdHours))*60;
 for(const segment of segments.sort((a,b)=>a.instant-b.instant||a.id.localeCompare(b.id))){const before=weeks.get(segment.week)||0,regular=overtimeEnabled?Math.min(segment.minutes,Math.max(0,threshold-before)):segment.minutes;weeks.set(segment.week,before+segment.minutes);if(!segment.selected)continue;regularMinutes+=regular;overtimeMinutes+=segment.minutes-regular;totalMinutes+=segment.minutes;}
 return {regularMinutes,overtimeMinutes,totalMinutes,entriesCount};
}
export function earningAmounts(regularMinutes:number,overtimeMinutes:number,rate:number,overtimeRate:number){const regularPay=money(regularMinutes/60*rate),otPay=money(overtimeMinutes/60*overtimeRate);return {regularPay,otPay,grossPay:money(regularPay+otPay)};}
export function lineTotals(earnings:any[],deductions:any[]){const cents=(value:any)=>Math.round(money(Number(value||0))*100);const gross=earnings.reduce((sum,line)=>sum+cents(line.amount),0),deduct=deductions.filter(line=>!line.employerPaid).reduce((sum,line)=>sum+cents(line.amount),0);if(!Number.isFinite(gross)||!Number.isFinite(deduct)||gross<0||deduct<0)throw Error('Enter valid non-negative earning and deduction amounts');return {grossPay:gross/100,totalDeductions:deduct/100,netPay:(gross-deduct)/100};}
export function configuredDeductionItems(gross:number,settings:any,custom:any[]){if(!settings.deductionsEnabled)return [];const items:Array<{type:string;description:string;amount:number}>=[];for(const [prefix,type,description] of [['federalTax','tax','Federal Tax'],['provincialTax','provincial_tax','Provincial Tax'],['cpp','cpp','CPP'],['ei','ei','EI']]){if(settings[prefix+'Mode']!=='percent')continue;const value=Number(settings[prefix+'Percent']||0);if(!Number.isFinite(value)||value<0||value>100)throw Error('Enter valid configured deduction percentages');if(value>0)items.push({type,description,amount:money(gross*value/100)});}for(const deduction of custom.filter(item=>item.isActive)){const value=Number(deduction.value||0);if(!Number.isFinite(value)||value<0||(deduction.type==='percent'&&value>100))throw Error('Enter valid custom deduction values');items.push({type:'other',description:deduction.label,amount:money(deduction.type==='percent'?gross*value/100:value)});}return items;}
export function payStubHoursLabel(stub:any){const minutes=stub.totalMinutesSnapshot;return minutes==null?`${Number(stub.totalHours||0).toFixed(2)}h`:`${Math.floor(minutes/60)}h ${minutes%60}m`;}
