import { useEffect, useRef, useState } from "react";
import { useParams } from "wouter";
import { apiRequest } from "@/lib/queryClient";
import { ArrowLeft, ArrowRight, Check, Clock3, Eye, LockKeyhole, PenLine, Plus, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const TYPES = ["injury/illness", "near miss", "property/equipment damage", "slip/trip/fall", "chemical exposure", "struck by/against", "cut/laceration", "burn", "repetitive strain/overexertion", "vehicle/forklift", "fire/explosion", "other"];
const TREATMENT = ["none", "first aid", "medical clinic", "emergency department"];
const ACTIONS = ["area secured", "supervisor notified", "first aid provided", "equipment removed from service", "work paused", "emergency services called", "cleanup completed"];
const steps = ["Access", "Incident", "People", "Evidence", "Review"];
type Person = { name: string; role: string; contact: string };
type Photo = { file: File; caption: string; evidenceType: string; url: string };
type Form = { employeeId: string; password: string; companySite: string; departmentCrew: string; exactLocation: string; incidentDate: string; incidentTime: string; shift: string; cleanerName: string; cleanerRole: string; incidentTypes: string[]; orderedDescription: string; injuryBodyParts: string; injuryNature: string; treatmentLevel: string; witnesses: Person[]; immediateActions: string[]; immediateActionNotes: string; typedCleanerName: string; declarationAccepted: boolean; signatureDataUrl: string };
const empty: Form = { employeeId: "", password: "", companySite: "", departmentCrew: "", exactLocation: "", incidentDate: "", incidentTime: "", shift: "", cleanerName: "", cleanerRole: "", incidentTypes: [], orderedDescription: "", injuryBodyParts: "", injuryNature: "", treatmentLevel: "", witnesses: [], immediateActions: [], immediateActionNotes: "", typedCleanerName: "", declarationAccepted: false, signatureDataUrl: "" };

export default function PublicIncident({ clientView = false }: { clientView?: boolean }) {
  const { token } = useParams<{ token: string }>();
  const [form, setForm] = useState<Form>(empty); const [meta, setMeta] = useState<any>(null); const [auth, setAuth] = useState(clientView); const [step, setStep] = useState(clientView ? 1 : 0); const [photos, setPhotos] = useState<Photo[]>([]); const [existingEvidence, setExistingEvidence] = useState<any[]>([]); const [selectedPhoto, setSelectedPhoto] = useState<Photo | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [done, setDone] = useState(false);
  const canvas = useRef<HTMLCanvasElement>(null); const drawing = useRef(false);
  const update = (key: keyof Form, value: any) => setForm(v => ({ ...v, [key]: value }));
  const cleanerPayload = () => ({
    companySiteName: form.companySite,
    departmentCrew: form.departmentCrew,
    exactLocation: form.exactLocation,
    incidentDate: form.incidentDate,
    incidentTime: form.incidentTime,
    shift: form.shift,
    cleanerName: form.cleanerName,
    cleanerRole: form.cleanerRole,
    incidentTypes: form.incidentTypes,
    description: form.orderedDescription,
    injuryDetails: { bodyParts: form.injuryBodyParts, nature: form.injuryNature, treatmentLevel: form.treatmentLevel },
    witnesses: form.witnesses,
    immediateActions: form.immediateActions,
    immediateActionsNotes: form.immediateActionNotes,
    cleanerSignerName: form.typedCleanerName,
    cleanerSignatureDataUrl: form.signatureDataUrl,
    declarationAccepted: form.declarationAccepted,
  });
  useEffect(() => { apiRequest("GET", `/api/public/incidents/${token}`).then(r => r.json()).then(data => { setMeta(data); const assigned = data.assignedEmployee ?? data.employee; if (assigned) setForm(v => ({ ...v, cleanerName: `${assigned.firstName ?? ""} ${assigned.lastName ?? ""}`.trim(), cleanerRole: assigned.role ?? v.cleanerRole, companySite: data.siteName ?? data.companySite ?? v.companySite })); }).catch(() => setError("This request is unavailable or has expired.")); }, [token]);
  useEffect(() => { if (!auth || clientView) return; apiRequest("GET", `/api/employee/incidents/${token}/draft`).then(r => r.json()).then(d => { const draft = d.cleanerDraft ?? {}; const injuryDetails = draft.injuryDetails ?? {}; setForm(v => ({ ...v, companySite: draft.companySiteName ?? v.companySite, departmentCrew: draft.departmentCrew ?? v.departmentCrew, exactLocation: draft.exactLocation ?? v.exactLocation, incidentDate: draft.incidentDate ?? v.incidentDate, incidentTime: draft.incidentTime ?? v.incidentTime, shift: draft.shift ?? v.shift, cleanerName: draft.cleanerName ?? v.cleanerName, cleanerRole: draft.cleanerRole ?? v.cleanerRole, incidentTypes: draft.incidentTypes ?? v.incidentTypes, orderedDescription: draft.description ?? v.orderedDescription, injuryBodyParts: injuryDetails.bodyParts ?? v.injuryBodyParts, injuryNature: injuryDetails.nature ?? v.injuryNature, treatmentLevel: injuryDetails.treatmentLevel ?? v.treatmentLevel, witnesses: draft.witnesses ?? v.witnesses, immediateActions: draft.immediateActions ?? v.immediateActions, immediateActionNotes: draft.immediateActionsNotes ?? v.immediateActionNotes, typedCleanerName: draft.cleanerSignerName ?? v.typedCleanerName, signatureDataUrl: draft.cleanerSignatureDataUrl ?? v.signatureDataUrl })); setExistingEvidence(d.evidence ?? []); }).catch(() => undefined); }, [auth, clientView, token]);
  useEffect(() => { if (!auth || clientView || step < 1) return; const timer = window.setTimeout(() => { setSaving(true); apiRequest("PATCH", `/api/employee/incidents/${token}/draft`, cleanerPayload()).finally(() => setSaving(false)); }, 650); return () => window.clearTimeout(timer); }, [form, auth, clientView, step, token]);
  const injury = form.incidentTypes.includes("injury/illness") || form.incidentTypes.includes("slip/trip/fall") || form.incidentTypes.includes("chemical exposure") || form.incidentTypes.includes("burn") || form.incidentTypes.includes("cut/laceration");
  async function login() { try { await apiRequest("POST", `/api/public/incidents/${token}/authenticate`, { employeeId: form.employeeId, password: form.password }); setAuth(true); setStep(1); } catch { setError("Employee ID or password was not accepted."); } }
  async function uploadEvidence() {
    for (const photo of photos) {
      const body = new FormData();
      body.append("file", photo.file);
      body.append("caption", photo.caption);
      body.append("evidenceType", photo.evidenceType);
      const response = await fetch(`/api/employee/incidents/${token}/evidence`, {
        method: "POST",
        body,
        credentials: "include",
      });
      if (!response.ok) throw new Error("Evidence upload failed");
    }
  }
  async function submit() { if (!form.exactLocation || !form.incidentDate || !form.incidentTime || !form.orderedDescription || photos.length + existingEvidence.length < 1 || !form.typedCleanerName || !form.signatureDataUrl) { setError("Complete the required fields, add at least one photo, and sign before submitting."); return; } try { await uploadEvidence(); await apiRequest("POST", `/api/employee/incidents/${token}/submit`, cleanerPayload()); setDone(true); } catch { setError("We could not submit this report. Your draft is still saved."); } }
  function choosePhotos(e: React.ChangeEvent<HTMLInputElement>) { const selected = Array.from(e.target.files ?? []).slice(0, 20 - photos.length); setPhotos(v => [...v, ...selected.map(file => ({ file, caption: "", evidenceType: "incident photo", url: URL.createObjectURL(file) }))]); }
  function draw(e: React.PointerEvent<HTMLCanvasElement>) { const c = canvas.current; if (!c || !drawing.current) return; const r = c.getBoundingClientRect(); const ctx = c.getContext("2d"); if (!ctx) return; ctx.lineWidth = 2; ctx.lineCap = "round"; ctx.strokeStyle = "#163842"; ctx.lineTo(e.clientX-r.left, e.clientY-r.top); ctx.stroke(); update("signatureDataUrl", c.toDataURL("image/png")); }
  if (error && !meta) return <Shell><State title="Request unavailable" detail={error} /></Shell>;
  if (clientView) return <ClientReport token={token} meta={meta} />;
  if (done) return <Shell><State success title="Report received" detail="Your report is locked and has been sent to your supervisor." /></Shell>;
  return <Shell><div className="mx-auto max-w-2xl"><Header saving={saving} title="Work incident report" /><div className="mb-6 flex gap-1">{steps.map((s, i) => <div key={s} className={`h-1 flex-1 rounded ${i <= step ? "bg-primary" : "bg-muted"}`} title={s} />)}</div>{!auth ? <Card className="shadow-none"><CardContent className="space-y-5 p-6"><h2 className="text-lg font-semibold">Confirm your access</h2><p className="text-sm text-muted-foreground">Use the employee ID and password provided by your supervisor.</p><Field label="Employee ID"><Input value={form.employeeId} onChange={e => update("employeeId", e.target.value)} /></Field><Field label="Password"><Input type="password" value={form.password} onChange={e => update("password", e.target.value)} /></Field>{error && <p className="text-sm text-destructive">{error}</p>}<Button className="w-full" onClick={login}>Continue <ArrowRight className="ml-2 h-4 w-4" /></Button><p className="flex items-center gap-2 text-xs text-muted-foreground"><LockKeyhole className="h-3.5 w-3.5" />Private to your organization.</p></CardContent></Card> : <Card className="shadow-none"><CardContent className="space-y-6 p-5 sm:p-7">
    {step === 1 && <Section title="Incident facts" note="Record the scene in order. Required fields are marked."><div className="grid gap-4 sm:grid-cols-2"><Field label="Company / site *"><Input value={form.companySite} onChange={e => update("companySite", e.target.value)} /></Field><Field label="Department / crew"><Input value={form.departmentCrew} onChange={e => update("departmentCrew", e.target.value)} /></Field><Field label="Exact location *"><Input value={form.exactLocation} onChange={e => update("exactLocation", e.target.value)} /></Field><Field label="Shift"><Input value={form.shift} onChange={e => update("shift", e.target.value)} placeholder="Day, evening, overnight" /></Field><Field label="Incident date *"><Input type="date" value={form.incidentDate} onChange={e => update("incidentDate", e.target.value)} /></Field><Field label="Incident time *"><Input type="time" value={form.incidentTime} onChange={e => update("incidentTime", e.target.value)} /></Field><Field label="Cleaner name"><Input value={form.cleanerName} onChange={e => update("cleanerName", e.target.value)} /></Field><Field label="Role"><Input value={form.cleanerRole} onChange={e => update("cleanerRole", e.target.value)} /></Field></div><Field label="Incident type *"><div className="grid gap-2 sm:grid-cols-2">{TYPES.map(type => <label key={type} className="flex gap-2 text-sm"><input type="checkbox" checked={form.incidentTypes.includes(type)} onChange={e => update("incidentTypes", e.target.checked ? [...form.incidentTypes, type] : form.incidentTypes.filter(x => x !== type))} />{type}</label>)}</div></Field><Field label="Ordered description *"><Textarea rows={8} value={form.orderedDescription} onChange={e => update("orderedDescription", e.target.value)} placeholder="1. What happened first? 2. What happened next? 3. What was done immediately?" /></Field>{injury && <div className="space-y-4 rounded-lg border border-amber-200 bg-amber-50/50 p-4"><p className="text-sm font-medium">Injury / exposure details</p><Field label="Body parts affected"><Input value={form.injuryBodyParts} onChange={e => update("injuryBodyParts", e.target.value)} /></Field><Field label="Nature of injury"><Input value={form.injuryNature} onChange={e => update("injuryNature", e.target.value)} placeholder="Bruise, strain, burn, irritation…" /></Field><Field label="Treatment level"><div className="flex flex-wrap gap-3">{TREATMENT.map(x => <label key={x} className="flex gap-2 text-sm"><input type="radio" name="treatment" checked={form.treatmentLevel === x} onChange={() => update("treatmentLevel", x)} />{x}</label>)}</div></Field></div>}</Section>}
    {step === 2 && <Section title="People and witnesses" note="Add everyone who saw or was involved."><Field label="Witnesses"><div className="space-y-3">{form.witnesses.map((person, i) => <div className="grid gap-2 rounded-lg border p-3 sm:grid-cols-3" key={i}><Input placeholder="Name" value={person.name} onChange={e => update("witnesses", form.witnesses.map((p,n) => n===i ? {...p,name:e.target.value} : p))} /><Input placeholder="Role" value={person.role} onChange={e => update("witnesses", form.witnesses.map((p,n) => n===i ? {...p,role:e.target.value} : p))} /><Input placeholder="Phone or email" value={person.contact} onChange={e => update("witnesses", form.witnesses.map((p,n) => n===i ? {...p,contact:e.target.value} : p))} /></div>)}</div><Button type="button" variant="outline" onClick={() => update("witnesses", [...form.witnesses, { name: "", role: "", contact: "" }])}><Plus className="mr-2 h-4 w-4" />Add witness</Button></Field></Section>}
    {step === 3 && <Section title="Photos and evidence" note="At least one photo is required. Use your camera or choose from your device."><label className="flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed p-9 text-center"><Upload className="h-6 w-6 text-primary" /><span className="mt-2 text-sm font-medium">Take or upload photos</span><span className="mt-1 text-xs text-muted-foreground">Up to 20 photos · captions required for the best record</span><input type="file" accept="image/*" capture="environment" multiple className="hidden" onChange={choosePhotos} /></label>{photos.length + existingEvidence.length === 0 && <p className="text-sm text-destructive">Add at least one photo before continuing.</p>}<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{existingEvidence.map((item: any) => <a key={item.id} href={`/api/employee/incidents/${token}/evidence/${item.id}`} target="_blank" rel="noreferrer" className="overflow-hidden rounded-lg border"><img src={`/api/employee/incidents/${token}/evidence/${item.id}`} className="aspect-square w-full object-cover" alt={item.caption ?? "Incident evidence"} /><p className="p-2 text-xs">{item.caption || item.evidenceType || "Uploaded evidence"}</p></a>)}{photos.map((photo, i) => <div key={photo.url} className="overflow-hidden rounded-lg border"><button type="button" onClick={() => setSelectedPhoto(photo)} className="relative block w-full"><img src={photo.url} className="aspect-square w-full object-cover" alt="" /><Eye className="absolute bottom-2 right-2 rounded bg-white/90 p-1 text-slate-700" /></button><div className="space-y-2 p-2"><Input value={photo.caption} placeholder="Caption" onChange={e => setPhotos(v => v.map((p,n) => n===i ? {...p,caption:e.target.value} : p))} /><Input value={photo.evidenceType} placeholder="Evidence type" onChange={e => setPhotos(v => v.map((p,n) => n===i ? {...p,evidenceType:e.target.value} : p))} /></div></div>)}</div>{selectedPhoto && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4" onClick={() => setSelectedPhoto(null)}><button className="absolute right-5 top-5 text-white"><X /></button><img src={selectedPhoto.url} className="max-h-[90vh] max-w-full rounded-lg object-contain" alt={selectedPhoto.caption} /></div>}</Section>}
    {step === 4 && <Section title="Immediate action and declaration" note="Document what was done to make the area safe."><Field label="Immediate actions"><div className="grid gap-2 sm:grid-cols-2">{ACTIONS.map(action => <label key={action} className="flex gap-2 text-sm"><input type="checkbox" checked={form.immediateActions.includes(action)} onChange={e => update("immediateActions", e.target.checked ? [...form.immediateActions, action] : form.immediateActions.filter(x => x !== action))} />{action}</label>)}</div></Field><Field label="Action notes"><Textarea rows={5} value={form.immediateActionNotes} onChange={e => update("immediateActionNotes", e.target.value)} /></Field><Field label="Type your full name *"><Input value={form.typedCleanerName} onChange={e => update("typedCleanerName", e.target.value)} /></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.declarationAccepted} onChange={e => update("declarationAccepted", e.target.checked)} />I confirm this statement is accurate to the best of my knowledge.</label><div><Label className="flex items-center gap-2"><PenLine className="h-3.5 w-3.5" />Signature *</Label><canvas ref={canvas} width={560} height={150} onPointerDown={e => { drawing.current=true; const ctx=canvas.current?.getContext("2d"); const r=canvas.current?.getBoundingClientRect(); ctx?.beginPath(); ctx?.moveTo(e.clientX-(r?.left ?? 0),e.clientY-(r?.top ?? 0)); }} onPointerUp={() => drawing.current=false} onPointerMove={draw} className="mt-2 h-32 w-full touch-none rounded-lg border bg-white" /><p className="mt-1 text-xs text-muted-foreground">The signature date will be recorded automatically.</p></div></Section>}
    <div className="flex justify-between border-t pt-5"><Button variant="ghost" disabled={step === 1} onClick={() => setStep(v => v-1)}><ArrowLeft className="mr-2 h-4 w-4" />Back</Button>{step < 4 ? <Button disabled={step === 3 && photos.length + existingEvidence.length < 1} onClick={() => setStep(v => v+1)}>Continue <ArrowRight className="ml-2 h-4 w-4" /></Button> : <Button disabled={!form.declarationAccepted || !form.signatureDataUrl || !form.typedCleanerName} onClick={submit}>Submit immutable report <Check className="ml-2 h-4 w-4" /></Button>}</div>{error && <p className="text-sm text-destructive">{error}</p>}</CardContent></Card>}</div></Shell>;
}

function ClientReport({ token, meta }: { token: string; meta: any }) {
  const [name, setName] = useState(""); const [ack, setAck] = useState(false); const [signatureDataUrl, setSignatureDataUrl] = useState(""); const canvas = useRef<HTMLCanvasElement>(null); const drawing = useRef(false); const [sent, setSent] = useState(false);
  const report = meta?.report ?? meta ?? {};
  const draw = (e: React.PointerEvent<HTMLCanvasElement>) => { const c=canvas.current; if (!c || !drawing.current) return; const r=c.getBoundingClientRect(); const ctx=c.getContext("2d"); if (!ctx) return; ctx.lineWidth=2; ctx.lineCap="round"; ctx.strokeStyle="#163842"; ctx.lineTo(e.clientX-r.left,e.clientY-r.top); ctx.stroke(); setSignatureDataUrl(c.toDataURL("image/png")); };
  async function acknowledge() { await apiRequest("POST", `/api/public/incidents/${token}/acknowledge`, { signerName: name, signatureDataUrl, acknowledgementAccepted: ack }); setSent(true); }
  if (sent) return <Shell><State success title="Acknowledgment received" detail="The incident report is now marked resolved and acknowledged." /></Shell>;
  return <Shell><div className="mx-auto max-w-3xl"><Header title="Client incident report" /><Card className="shadow-none"><CardContent className="space-y-7 p-6"><div className="rounded-lg bg-muted/40 p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Incident summary</p><p className="mt-2 text-sm">{report.description ?? report.employeeStatement ?? report.summary ?? "—"}</p></div><div className="grid gap-4 sm:grid-cols-4"><Read label="Site" value={report.companySiteName ?? report.siteName} /><Read label="Location" value={report.exactLocation ?? report.areaAffected} /><Read label="Date" value={report.incidentDate} /><Read label="Shift" value={report.shift} /></div><div><Label>Photos</Label><div className="mt-2 grid grid-cols-2 gap-3 sm:grid-cols-4">{(report.evidence ?? []).map((p:any, i:number) => <img key={i} src={p.url ?? p.downloadUrl} className="aspect-square rounded-lg object-cover" alt={p.caption ?? ""} />)}</div></div><div><Label>Action / resolution</Label><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{report.actionsResolution ?? report.immediateAction ?? "—"}</p></div><div><Label>Preventive measures</Label><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{report.preventiveMeasures ?? report.nextSteps ?? "—"}</p></div><div className="grid gap-4 border-t pt-5 sm:grid-cols-2"><Read label="Cleaner signature" value={report.cleanerSignerName} /><Read label="Admin signature" value={report.adminSignerName} /></div><div className="space-y-4 border-t pt-5"><Field label="Client name"><Input value={name} onChange={e => setName(e.target.value)} /></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)} />I acknowledge receipt of this incident report and its resolution.</label><Label>Client signature (optional if acknowledged)</Label><canvas ref={canvas} width={600} height={120} onPointerDown={e=>{drawing.current=true;const c=canvas.current;const r=c?.getBoundingClientRect();c?.getContext("2d")?.moveTo(e.clientX-(r?.left??0),e.clientY-(r?.top??0));}} onPointerUp={()=>drawing.current=false} onPointerMove={draw} className="h-24 w-full touch-none rounded border bg-white" /><Button disabled={!ack || !name} onClick={acknowledge}>Acknowledge report <Check className="ml-2 h-4 w-4" /></Button></div></CardContent></Card></div></Shell>;
}
function Header({ saving, title }: { saving?: boolean; title: string }) { return <div className="mb-7 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.22em] text-primary">ClockField safety record</p><h1 className="mt-2 text-2xl font-semibold">{title}</h1></div>{saving !== undefined && <Badge variant="outline"><Clock3 className="mr-1.5 h-3 w-3" />{saving ? "Saving…" : "Saved"}</Badge>}</div>; }
function Field({ label, children }: any) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Section({ title, note, children }: any) { return <div className="space-y-5"><div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{note}</p></div>{children}</div>; }
function Read({ label, value }: any) { return <div><Label>{label}</Label><p className="mt-1 text-sm">{value || "—"}</p></div>; }
function State({ title, detail, success=false }: any) { return <div className="mx-auto max-w-md py-20 text-center">{success && <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check /></div>}<h1 className="mt-5 text-2xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{detail}</p></div>; }
function Shell({ children }: any) { return <div className="min-h-[100dvh] bg-[hsl(198_35%_97%)] px-4 py-5 text-[hsl(199_32%_16%)] sm:px-6 sm:py-8"><header className="mx-auto mb-8 flex max-w-3xl items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-md bg-[hsl(176_64%_35%)] text-white"><span className="font-mono text-xs">CF</span></div><span className="font-semibold">ClockField</span></header>{children}<footer className="mx-auto mt-10 flex max-w-3xl justify-center text-xs text-muted-foreground">Safety records are encrypted in transit and retained by your organization.</footer></div>; }
export function PublicIncidentClient() { return <PublicIncident clientView />; }